### ISSUE TITLE
Client 6.xx

### ISSUE THREAD

**Issue by asdqwe3124** [brandonros/nexustk#2]
Hi,

Can you tell me what should I change to make it work with client 6.89?

Thanks

**Comment by brandonros** [comment]
689 in hex

Regards,

Brandon
________________________________

**Comment by asdqwe3124** [comment]
Thanks for the reply.

689 in hex?
Can you tell me more details?

Thanks

**Comment by nmanley** [comment]
@asdqwe3124 Look at line 59 in client.js

**Comment by asdqwe3124** [comment]
@nmanley thanks for the reply, 
I've changed it, I also change the key since 6.x use different key.
but, still failed to login.
any idea?

**Comment by ASAPHAANING** [comment]
How did you go about finding the key?

**Comment by brandonros** [comment]
ASM OllyDbg reverse engineering.

Regards,

Brandon
________________________________

**Comment by ASAPHAANING** [comment]
Makes sense,
Is it a symmetric key used to encrypt and decrypt?

**Comment by brandonros** [comment]
Can you elaborate?

Regards,

Brandon
________________________________

**Comment by ASAPHAANING** [comment]
Of course! Is it the same key used for decryption and encryption? :) In asymmetric it's usually the public key of the receiver, you'd use the servers public key to encrypt and your private key to decrypt, but I assume this is not the case here from expecting your code!

The reason I'm asking is because I'd love to try this challenge without just using the key provided in the repo.

Appreciate you've open-sourced it, it's motivated me to try.

**Comment by brandonros** [comment]
You are giving KRU/Nexon way too much credit

It’s a bunch of XORing

It’s more like an encoding than encrypting lol

Regards,

Brandon
________________________________
